# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  market_data:
    class: UpdateMarketDataJob
    queue: default
    schedule: every day at 11:01

production:
  market_data:
    class: UpdateMarketDataJob
    queue: default
    schedule: every hour at minute 1

development:
  portfolio_composition:
    class: UpdateAllPortfolioCompositionJob
    queue: default
    schedule: every 4 hours

production:
  portfolio_composition:
    class: UpdateAllPortfolioCompositionJob
    queue: default
    schedule: every 4 hours
